/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param app 
 * @param environment 
 * @param platform Originating platform.
 * @param userId 
 * @param anonymousId 
 * @param deviceId 
 * @param appVersion 
 * @param buildNumber 
 * @param country 
 * @param locale 
 * @param timezone 
 * @param traits Free-form structured properties. Reserved keys: `_ctx` for SDK common context.
 */
@Serializable

data class IdentifyUserRequest (

    @SerialName(value = "app")
    val app: kotlin.String,

    @SerialName(value = "environment")
    val environment: IdentifyUserRequest.Environment? = Environment.production,

    /* Originating platform. */
    @SerialName(value = "platform")
    val platform: IdentifyUserRequest.Platform? = Platform.ios,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    @SerialName(value = "anonymousId")
    val anonymousId: kotlin.String? = null,

    @SerialName(value = "deviceId")
    val deviceId: kotlin.String? = null,

    @SerialName(value = "appVersion")
    val appVersion: kotlin.String? = null,

    @SerialName(value = "buildNumber")
    val buildNumber: kotlin.String? = null,

    @SerialName(value = "country")
    val country: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null,

    /* Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    @Contextual @SerialName(value = "traits")
    val traits: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * 
     *
     * Values: production,staging,development
     */
    @Serializable
    enum class Environment(val value: kotlin.String) {
        @SerialName(value = "production") production("production"),
        @SerialName(value = "staging") staging("staging"),
        @SerialName(value = "development") development("development");
    }
    /**
     * Originating platform.
     *
     * Values: ios,android,web,macos,server
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "ios") ios("ios"),
        @SerialName(value = "android") android("android"),
        @SerialName(value = "web") web("web"),
        @SerialName(value = "macos") macos("macos"),
        @SerialName(value = "server") server("server");
    }

}

