/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param app 
 * @param playInstallReferrer 
 * @param environment 
 * @param userId 
 * @param anonymousId 
 * @param platform 
 * @param source 
 * @param occurredAt 
 * @param properties Free-form structured properties. Reserved keys: `_ctx` for SDK common context.
 */
@Serializable

data class PlayInstallReferrerRequest (

    @SerialName(value = "app")
    val app: kotlin.String,

    @SerialName(value = "playInstallReferrer")
    val playInstallReferrer: kotlin.String,

    @SerialName(value = "environment")
    val environment: PlayInstallReferrerRequest.Environment? = Environment.production,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    @SerialName(value = "anonymousId")
    val anonymousId: kotlin.String? = null,

    @SerialName(value = "platform")
    val platform: PlayInstallReferrerRequest.Platform? = Platform.android,

    @SerialName(value = "source")
    val source: kotlin.String? = "native",

    @Contextual @SerialName(value = "occurredAt")
    val occurredAt: java.time.OffsetDateTime? = null,

    /* Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    @Contextual @SerialName(value = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * 
     *
     * Values: production,staging,development
     */
    @Serializable
    enum class Environment(val value: kotlin.String) {
        @SerialName(value = "production") production("production"),
        @SerialName(value = "staging") staging("staging"),
        @SerialName(value = "development") development("development");
    }
    /**
     * 
     *
     * Values: android
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "android") android("android");
    }

}

