/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `data` 
 * @param attributes 
 * @param messageId 
 * @param publishTime 
 */
@Serializable

data class PlayStoreWebhookRequestMessage (

    @SerialName(value = "data")
    val `data`: kotlin.String,

    @SerialName(value = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "messageId")
    val messageId: kotlin.String? = null,

    @SerialName(value = "publishTime")
    val publishTime: kotlin.String? = null

) {


}

