/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param version 
 * @param adNetworkId 
 * @param transactionId 
 * @param appId 
 * @param attributionSignature 
 * @param campaignId 
 * @param sourceIdentifier 
 * @param redownload 
 * @param sourceAppId 
 * @param sourceDomain 
 * @param fidelityType 
 * @param conversionValue 
 * @param coarseConversionValue 
 * @param didWin 
 * @param postbackSequenceIndex 
 */
@Serializable

data class SkanPostbackRequest (

    @SerialName(value = "version")
    val version: kotlin.String,

    @SerialName(value = "ad-network-id")
    val adNetworkId: kotlin.String,

    @SerialName(value = "transaction-id")
    val transactionId: kotlin.String,

    @SerialName(value = "app-id")
    val appId: kotlin.Int,

    @SerialName(value = "attribution-signature")
    val attributionSignature: kotlin.String,

    @SerialName(value = "campaign-id")
    val campaignId: kotlin.Int? = null,

    @SerialName(value = "source-identifier")
    val sourceIdentifier: kotlin.String? = null,

    @SerialName(value = "redownload")
    val redownload: kotlin.Boolean? = null,

    @SerialName(value = "source-app-id")
    val sourceAppId: kotlin.Int? = null,

    @SerialName(value = "source-domain")
    val sourceDomain: kotlin.String? = null,

    @SerialName(value = "fidelity-type")
    val fidelityType: kotlin.Int? = null,

    @SerialName(value = "conversion-value")
    val conversionValue: kotlin.Int? = null,

    @SerialName(value = "coarse-conversion-value")
    val coarseConversionValue: SkanPostbackRequest.CoarseConversionValue? = null,

    @SerialName(value = "did-win")
    val didWin: kotlin.Boolean? = null,

    @SerialName(value = "postback-sequence-index")
    val postbackSequenceIndex: kotlin.Int? = null

) : kotlin.collections.HashMap<String, kotlin.Any>()() {

    /**
     * 
     *
     * Values: low,medium,high
     */
    @Serializable
    enum class CoarseConversionValue(val value: kotlin.String) {
        @SerialName(value = "low") low("low"),
        @SerialName(value = "medium") medium("medium"),
        @SerialName(value = "high") high("high");
    }

}

