/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param app 
 * @param eventName 
 * @param environment 
 * @param platform Originating platform.
 * @param userId 
 * @param anonymousId 
 * @param deviceId 
 * @param appVersion 
 * @param buildNumber 
 * @param source 
 * @param country ISO-3166 alpha-2; server fills from Cloudflare if absent.
 * @param locale 
 * @param timezone 
 * @param attributionProvider 
 * @param attributionId 
 * @param occurredAt 
 * @param properties Free-form structured properties. Reserved keys: `_ctx` for SDK common context.
 * @param metricValue 
 * @param metricLabel 
 */
@Serializable

data class TrackEventRequest (

    @SerialName(value = "app")
    val app: kotlin.String,

    @SerialName(value = "eventName")
    val eventName: TrackEventRequest.EventName,

    @SerialName(value = "environment")
    val environment: TrackEventRequest.Environment? = Environment.production,

    /* Originating platform. */
    @SerialName(value = "platform")
    val platform: TrackEventRequest.Platform? = Platform.ios,

    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    @SerialName(value = "anonymousId")
    val anonymousId: kotlin.String? = null,

    @SerialName(value = "deviceId")
    val deviceId: kotlin.String? = null,

    @SerialName(value = "appVersion")
    val appVersion: kotlin.String? = null,

    @SerialName(value = "buildNumber")
    val buildNumber: kotlin.String? = null,

    @SerialName(value = "source")
    val source: kotlin.String? = "native",

    /* ISO-3166 alpha-2; server fills from Cloudflare if absent. */
    @SerialName(value = "country")
    val country: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null,

    @SerialName(value = "timezone")
    val timezone: kotlin.String? = null,

    @SerialName(value = "attributionProvider")
    val attributionProvider: kotlin.String? = null,

    @SerialName(value = "attributionId")
    val attributionId: kotlin.String? = null,

    @Contextual @SerialName(value = "occurredAt")
    val occurredAt: java.time.OffsetDateTime? = null,

    /* Free-form structured properties. Reserved keys: `_ctx` for SDK common context. */
    @Contextual @SerialName(value = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Contextual @SerialName(value = "metricValue")
    val metricValue: java.math.BigDecimal? = null,

    @SerialName(value = "metricLabel")
    val metricLabel: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: appPeriodFirst_open,appPeriodOpened,userPeriodCreated,sessionPeriodStarted,sessionPeriodEnded,acquisitionPeriodAttribution_resolved,app_storePeriodProduct_page_viewed,app_storePeriodInstall_attributed,onboardingPeriodStarted,onboardingPeriodCompleted,onboardingPeriodStep_viewed,onboardingPeriodStep_completed,onboardingPeriodStep_skipped,onboardingPeriodGoal_selected,onboardingPeriodPermission_prompted,onboardingPeriodPermission_granted,onboardingPeriodPermission_denied,activationPeriodCompleted,featurePeriodUsed,featurePeriodFirst_used,pagePeriodViewed,buttonPeriodClicked,goalPeriodCompleted,paywallPeriodOpened,paywallPeriodClosed,paywallPeriodUpgrade_clicked,paywallPeriodUpgrade_cancelled,paywallPeriodProducts_requested,paywallPeriodProducts_loaded,paywallPeriodProducts_failed,paywallPeriodOffer_eligible,paywallPeriodPlan_selected,paywallPeriodRestore_clicked,paywallPeriodRestore_completed,paywallPeriodRestore_failed,purchasePeriodStarted,purchasePeriodCompleted,purchasePeriodFailed,purchasePeriodRefunded,trialPeriodEligible,trialPeriodIneligible,trialPeriodStarted,trialPeriodConverted,trialPeriodCancelled,trialPeriodExpired,trialPeriodBilling_retry_started,subscriptionPeriodStarted,subscriptionPeriodRenewed,subscriptionPeriodCancelled,subscriptionPeriodExpired,subscriptionPeriodBilling_issue,subscriptionPeriodGrace_period_started,subscriptionPeriodRecovered,subscriptionPeriodRefunded,subscriptionPeriodPrice_increase_accepted,subscriptionPeriodPrice_increase_declined,revenuePeriodReceived,referralPeriodSent,referralPeriodAccepted,reviewPeriodPrompted,reviewPeriodSubmitted,notificationPeriodReceived,notificationPeriodOpened,errorPeriodOccurred
     */
    @Serializable
    enum class EventName(val value: kotlin.String) {
        @SerialName(value = "app.first_open") appPeriodFirst_open("app.first_open"),
        @SerialName(value = "app.opened") appPeriodOpened("app.opened"),
        @SerialName(value = "user.created") userPeriodCreated("user.created"),
        @SerialName(value = "session.started") sessionPeriodStarted("session.started"),
        @SerialName(value = "session.ended") sessionPeriodEnded("session.ended"),
        @SerialName(value = "acquisition.attribution_resolved") acquisitionPeriodAttribution_resolved("acquisition.attribution_resolved"),
        @SerialName(value = "app_store.product_page_viewed") app_storePeriodProduct_page_viewed("app_store.product_page_viewed"),
        @SerialName(value = "app_store.install_attributed") app_storePeriodInstall_attributed("app_store.install_attributed"),
        @SerialName(value = "onboarding.started") onboardingPeriodStarted("onboarding.started"),
        @SerialName(value = "onboarding.completed") onboardingPeriodCompleted("onboarding.completed"),
        @SerialName(value = "onboarding.step_viewed") onboardingPeriodStep_viewed("onboarding.step_viewed"),
        @SerialName(value = "onboarding.step_completed") onboardingPeriodStep_completed("onboarding.step_completed"),
        @SerialName(value = "onboarding.step_skipped") onboardingPeriodStep_skipped("onboarding.step_skipped"),
        @SerialName(value = "onboarding.goal_selected") onboardingPeriodGoal_selected("onboarding.goal_selected"),
        @SerialName(value = "onboarding.permission_prompted") onboardingPeriodPermission_prompted("onboarding.permission_prompted"),
        @SerialName(value = "onboarding.permission_granted") onboardingPeriodPermission_granted("onboarding.permission_granted"),
        @SerialName(value = "onboarding.permission_denied") onboardingPeriodPermission_denied("onboarding.permission_denied"),
        @SerialName(value = "activation.completed") activationPeriodCompleted("activation.completed"),
        @SerialName(value = "feature.used") featurePeriodUsed("feature.used"),
        @SerialName(value = "feature.first_used") featurePeriodFirst_used("feature.first_used"),
        @SerialName(value = "page.viewed") pagePeriodViewed("page.viewed"),
        @SerialName(value = "button.clicked") buttonPeriodClicked("button.clicked"),
        @SerialName(value = "goal.completed") goalPeriodCompleted("goal.completed"),
        @SerialName(value = "paywall.opened") paywallPeriodOpened("paywall.opened"),
        @SerialName(value = "paywall.closed") paywallPeriodClosed("paywall.closed"),
        @SerialName(value = "paywall.upgrade_clicked") paywallPeriodUpgrade_clicked("paywall.upgrade_clicked"),
        @SerialName(value = "paywall.upgrade_cancelled") paywallPeriodUpgrade_cancelled("paywall.upgrade_cancelled"),
        @SerialName(value = "paywall.products_requested") paywallPeriodProducts_requested("paywall.products_requested"),
        @SerialName(value = "paywall.products_loaded") paywallPeriodProducts_loaded("paywall.products_loaded"),
        @SerialName(value = "paywall.products_failed") paywallPeriodProducts_failed("paywall.products_failed"),
        @SerialName(value = "paywall.offer_eligible") paywallPeriodOffer_eligible("paywall.offer_eligible"),
        @SerialName(value = "paywall.plan_selected") paywallPeriodPlan_selected("paywall.plan_selected"),
        @SerialName(value = "paywall.restore_clicked") paywallPeriodRestore_clicked("paywall.restore_clicked"),
        @SerialName(value = "paywall.restore_completed") paywallPeriodRestore_completed("paywall.restore_completed"),
        @SerialName(value = "paywall.restore_failed") paywallPeriodRestore_failed("paywall.restore_failed"),
        @SerialName(value = "purchase.started") purchasePeriodStarted("purchase.started"),
        @SerialName(value = "purchase.completed") purchasePeriodCompleted("purchase.completed"),
        @SerialName(value = "purchase.failed") purchasePeriodFailed("purchase.failed"),
        @SerialName(value = "purchase.refunded") purchasePeriodRefunded("purchase.refunded"),
        @SerialName(value = "trial.eligible") trialPeriodEligible("trial.eligible"),
        @SerialName(value = "trial.ineligible") trialPeriodIneligible("trial.ineligible"),
        @SerialName(value = "trial.started") trialPeriodStarted("trial.started"),
        @SerialName(value = "trial.converted") trialPeriodConverted("trial.converted"),
        @SerialName(value = "trial.cancelled") trialPeriodCancelled("trial.cancelled"),
        @SerialName(value = "trial.expired") trialPeriodExpired("trial.expired"),
        @SerialName(value = "trial.billing_retry_started") trialPeriodBilling_retry_started("trial.billing_retry_started"),
        @SerialName(value = "subscription.started") subscriptionPeriodStarted("subscription.started"),
        @SerialName(value = "subscription.renewed") subscriptionPeriodRenewed("subscription.renewed"),
        @SerialName(value = "subscription.cancelled") subscriptionPeriodCancelled("subscription.cancelled"),
        @SerialName(value = "subscription.expired") subscriptionPeriodExpired("subscription.expired"),
        @SerialName(value = "subscription.billing_issue") subscriptionPeriodBilling_issue("subscription.billing_issue"),
        @SerialName(value = "subscription.grace_period_started") subscriptionPeriodGrace_period_started("subscription.grace_period_started"),
        @SerialName(value = "subscription.recovered") subscriptionPeriodRecovered("subscription.recovered"),
        @SerialName(value = "subscription.refunded") subscriptionPeriodRefunded("subscription.refunded"),
        @SerialName(value = "subscription.price_increase_accepted") subscriptionPeriodPrice_increase_accepted("subscription.price_increase_accepted"),
        @SerialName(value = "subscription.price_increase_declined") subscriptionPeriodPrice_increase_declined("subscription.price_increase_declined"),
        @SerialName(value = "revenue.received") revenuePeriodReceived("revenue.received"),
        @SerialName(value = "referral.sent") referralPeriodSent("referral.sent"),
        @SerialName(value = "referral.accepted") referralPeriodAccepted("referral.accepted"),
        @SerialName(value = "review.prompted") reviewPeriodPrompted("review.prompted"),
        @SerialName(value = "review.submitted") reviewPeriodSubmitted("review.submitted"),
        @SerialName(value = "notification.received") notificationPeriodReceived("notification.received"),
        @SerialName(value = "notification.opened") notificationPeriodOpened("notification.opened"),
        @SerialName(value = "error.occurred") errorPeriodOccurred("error.occurred");
    }
    /**
     * 
     *
     * Values: production,staging,development
     */
    @Serializable
    enum class Environment(val value: kotlin.String) {
        @SerialName(value = "production") production("production"),
        @SerialName(value = "staging") staging("staging"),
        @SerialName(value = "development") development("development");
    }
    /**
     * Originating platform.
     *
     * Values: ios,android,web,macos,server
     */
    @Serializable
    enum class Platform(val value: kotlin.String) {
        @SerialName(value = "ios") ios("ios"),
        @SerialName(value = "android") android("android"),
        @SerialName(value = "web") web("web"),
        @SerialName(value = "macos") macos("macos"),
        @SerialName(value = "server") server("server");
    }

}

