/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.gtmeasy.growth.api.models.AppleAttributionRequest
import com.gtmeasy.growth.api.models.ErrorResponse
import com.gtmeasy.growth.api.models.IngestEventResponse
import com.gtmeasy.growth.api.models.PlayInstallReferrerRequest
import com.gtmeasy.growth.api.models.WebReferrerRequest

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.gtmeasy.growth.api.infrastructure.ApiClient
import com.gtmeasy.growth.api.infrastructure.ApiResponse
import com.gtmeasy.growth.api.infrastructure.ClientException
import com.gtmeasy.growth.api.infrastructure.ClientError
import com.gtmeasy.growth.api.infrastructure.ServerException
import com.gtmeasy.growth.api.infrastructure.ServerError
import com.gtmeasy.growth.api.infrastructure.MultiValueMap
import com.gtmeasy.growth.api.infrastructure.PartConfig
import com.gtmeasy.growth.api.infrastructure.RequestConfig
import com.gtmeasy.growth.api.infrastructure.RequestMethod
import com.gtmeasy.growth.api.infrastructure.ResponseType
import com.gtmeasy.growth.api.infrastructure.Success
import com.gtmeasy.growth.api.infrastructure.toMultiValue
import com.gtmeasy.growth.api.infrastructure.Serializer

open class AttributionApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://www.gtmeasy.com/api/v1/growth")
        }
    }

    /**
     * POST /attribution/apple-search-ads
     * Submit an Apple Search Ads attribution token
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param appleAttributionRequest 
     * @return IngestEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun attributionAppleSearchAdsPost(xGtmGrowthKey: kotlin.String, appleAttributionRequest: AppleAttributionRequest) : IngestEventResponse = withContext(Dispatchers.IO) {
        val localVarResponse = attributionAppleSearchAdsPostWithHttpInfo(xGtmGrowthKey = xGtmGrowthKey, appleAttributionRequest = appleAttributionRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /attribution/apple-search-ads
     * Submit an Apple Search Ads attribution token
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param appleAttributionRequest 
     * @return ApiResponse<IngestEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun attributionAppleSearchAdsPostWithHttpInfo(xGtmGrowthKey: kotlin.String, appleAttributionRequest: AppleAttributionRequest) : ApiResponse<IngestEventResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = attributionAppleSearchAdsPostRequestConfig(xGtmGrowthKey = xGtmGrowthKey, appleAttributionRequest = appleAttributionRequest)

        return@withContext request<AppleAttributionRequest, IngestEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation attributionAppleSearchAdsPost
     *
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param appleAttributionRequest 
     * @return RequestConfig
     */
    fun attributionAppleSearchAdsPostRequestConfig(xGtmGrowthKey: kotlin.String, appleAttributionRequest: AppleAttributionRequest) : RequestConfig<AppleAttributionRequest> {
        val localVariableBody = appleAttributionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xGtmGrowthKey.apply { localVariableHeaders["x-gtm-growth-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/attribution/apple-search-ads",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /attribution/play-install-referrer
     * Submit a Google Play install referrer string
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param playInstallReferrerRequest 
     * @return IngestEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun attributionPlayInstallReferrerPost(xGtmGrowthKey: kotlin.String, playInstallReferrerRequest: PlayInstallReferrerRequest) : IngestEventResponse = withContext(Dispatchers.IO) {
        val localVarResponse = attributionPlayInstallReferrerPostWithHttpInfo(xGtmGrowthKey = xGtmGrowthKey, playInstallReferrerRequest = playInstallReferrerRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /attribution/play-install-referrer
     * Submit a Google Play install referrer string
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param playInstallReferrerRequest 
     * @return ApiResponse<IngestEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun attributionPlayInstallReferrerPostWithHttpInfo(xGtmGrowthKey: kotlin.String, playInstallReferrerRequest: PlayInstallReferrerRequest) : ApiResponse<IngestEventResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = attributionPlayInstallReferrerPostRequestConfig(xGtmGrowthKey = xGtmGrowthKey, playInstallReferrerRequest = playInstallReferrerRequest)

        return@withContext request<PlayInstallReferrerRequest, IngestEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation attributionPlayInstallReferrerPost
     *
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param playInstallReferrerRequest 
     * @return RequestConfig
     */
    fun attributionPlayInstallReferrerPostRequestConfig(xGtmGrowthKey: kotlin.String, playInstallReferrerRequest: PlayInstallReferrerRequest) : RequestConfig<PlayInstallReferrerRequest> {
        val localVariableBody = playInstallReferrerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xGtmGrowthKey.apply { localVariableHeaders["x-gtm-growth-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/attribution/play-install-referrer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /attribution/web-referrer
     * Submit a web referrer URL + click id
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param webReferrerRequest 
     * @return IngestEventResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun attributionWebReferrerPost(xGtmGrowthKey: kotlin.String, webReferrerRequest: WebReferrerRequest) : IngestEventResponse = withContext(Dispatchers.IO) {
        val localVarResponse = attributionWebReferrerPostWithHttpInfo(xGtmGrowthKey = xGtmGrowthKey, webReferrerRequest = webReferrerRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestEventResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /attribution/web-referrer
     * Submit a web referrer URL + click id
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param webReferrerRequest 
     * @return ApiResponse<IngestEventResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun attributionWebReferrerPostWithHttpInfo(xGtmGrowthKey: kotlin.String, webReferrerRequest: WebReferrerRequest) : ApiResponse<IngestEventResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = attributionWebReferrerPostRequestConfig(xGtmGrowthKey = xGtmGrowthKey, webReferrerRequest = webReferrerRequest)

        return@withContext request<WebReferrerRequest, IngestEventResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation attributionWebReferrerPost
     *
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param webReferrerRequest 
     * @return RequestConfig
     */
    fun attributionWebReferrerPostRequestConfig(xGtmGrowthKey: kotlin.String, webReferrerRequest: WebReferrerRequest) : RequestConfig<WebReferrerRequest> {
        val localVariableBody = webReferrerRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xGtmGrowthKey.apply { localVariableHeaders["x-gtm-growth-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/attribution/web-referrer",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
