/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.gtmeasy.growth.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.gtmeasy.growth.api.models.ErrorResponse
import com.gtmeasy.growth.api.models.IdentifyUserRequest
import com.gtmeasy.growth.api.models.IngestUserResponse

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import com.gtmeasy.growth.api.infrastructure.ApiClient
import com.gtmeasy.growth.api.infrastructure.ApiResponse
import com.gtmeasy.growth.api.infrastructure.ClientException
import com.gtmeasy.growth.api.infrastructure.ClientError
import com.gtmeasy.growth.api.infrastructure.ServerException
import com.gtmeasy.growth.api.infrastructure.ServerError
import com.gtmeasy.growth.api.infrastructure.MultiValueMap
import com.gtmeasy.growth.api.infrastructure.PartConfig
import com.gtmeasy.growth.api.infrastructure.RequestConfig
import com.gtmeasy.growth.api.infrastructure.RequestMethod
import com.gtmeasy.growth.api.infrastructure.ResponseType
import com.gtmeasy.growth.api.infrastructure.Success
import com.gtmeasy.growth.api.infrastructure.toMultiValue
import com.gtmeasy.growth.api.infrastructure.Serializer

open class UsersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://www.gtmeasy.com/api/v1/growth")
        }
    }

    /**
     * POST /users
     * Identify a user / upsert traits
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param identifyUserRequest 
     * @return IngestUserResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    suspend fun usersPost(xGtmGrowthKey: kotlin.String, identifyUserRequest: IdentifyUserRequest) : IngestUserResponse = withContext(Dispatchers.IO) {
        val localVarResponse = usersPostWithHttpInfo(xGtmGrowthKey = xGtmGrowthKey, identifyUserRequest = identifyUserRequest)

        return@withContext when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as IngestUserResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /users
     * Identify a user / upsert traits
     * 
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param identifyUserRequest 
     * @return ApiResponse<IngestUserResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    suspend fun usersPostWithHttpInfo(xGtmGrowthKey: kotlin.String, identifyUserRequest: IdentifyUserRequest) : ApiResponse<IngestUserResponse?> = withContext(Dispatchers.IO) {
        val localVariableConfig = usersPostRequestConfig(xGtmGrowthKey = xGtmGrowthKey, identifyUserRequest = identifyUserRequest)

        return@withContext request<IdentifyUserRequest, IngestUserResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation usersPost
     *
     * @param xGtmGrowthKey SDK write key issued from the GTM Easy dashboard for this app.
     * @param identifyUserRequest 
     * @return RequestConfig
     */
    fun usersPostRequestConfig(xGtmGrowthKey: kotlin.String, identifyUserRequest: IdentifyUserRequest) : RequestConfig<IdentifyUserRequest> {
        val localVariableBody = identifyUserRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        xGtmGrowthKey.apply { localVariableHeaders["x-gtm-growth-key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/users",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
